// Recommendation action types
export const GET_RECOMMENDATIONS_REQUEST = "GET_RECOMMENDATIONS_REQUEST";
export const GET_RECOMMENDATIONS_SUCCESS = "GET_RECOMMENDATIONS_SUCCESS";
export const GET_RECOMMENDATIONS_FAILURE = "GET_RECOMMENDATIONS_FAILURE";

export const TRACK_INTERACTION_REQUEST = "TRACK_INTERACTION_REQUEST";
export const TRACK_INTERACTION_SUCCESS = "TRACK_INTERACTION_SUCCESS";
export const TRACK_INTERACTION_FAILURE = "TRACK_INTERACTION_FAILURE";

export const GET_RETRAINING_STATUS_REQUEST = "GET_RETRAINING_STATUS_REQUEST";
export const GET_RETRAINING_STATUS_SUCCESS = "GET_RETRAINING_STATUS_SUCCESS";
export const GET_RETRAINING_STATUS_FAILURE = "GET_RETRAINING_STATUS_FAILURE";

export const TRIGGER_RETRAINING_REQUEST = "TRIGGER_RETRAINING_REQUEST";
export const TRIGGER_RETRAINING_SUCCESS = "TRIGGER_RETRAINING_SUCCESS";
export const TRIGGER_RETRAINING_FAILURE = "TRIGGER_RETRAINING_FAILURE"; 